#=================================================
# https://github.com/danxiaonuo/zabbix-docker
# Description: Build zabbix using GitHub Actions
# Lisence: MIT
# Author: danxiaonuo
# Blog: https://www.danxiaonuo.com
#=================================================

name: 自动编译zabbix并上传镜像

# 设置触发条件
on:
  # 编辑文件触发开始编译
  push:
    paths:
      - 'Dockerfile'
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      build:
        description: 'build zabbix'
        required: true
        default: 'build zabbix'
  # 定时触发编译(每天早5点)
  #schedule:
  #   - cron: '0 21 * * *'
  # 点☆Star触发开始编译
  watch:  
     types: [started]
   
# 任务集
jobs:
  zabbix-build-base:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_TAG: latest
    
    # 运行步骤
    steps:
    
    # 检出master分支
    - name: 检出各个模块代码
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 安装 QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: 安装 docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: 登录 DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: 构建镜像并发布
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build-base/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/zabbix-build-base:${{ matrix.DOCKER_TAG }}
        
    - name: 上传至阿里云
      id: buildAndPushImage
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'registry.cn-hongkong.aliyuncs.com'
        namespaces: 'danxiaonuo'
        repository_name: 'zabbix-build-base'
        user_name: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
        image_version: ${{ matrix.DOCKER_TAG }}
        docker_file: 'build-base/.'


    - name: 删除旧的GitHub-workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 1    #保留多少个workflow不删除

  zabbix-build-mysql:
    # 依赖环境
    needs: [ zabbix-build-base ]
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_TAG: latest

    # 运行步骤
    steps:

      # 检出master分支
      - name: 检出各个模块代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: 安装 docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建镜像并发布
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build-mysql/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zabbix-build-mysql:${{ matrix.DOCKER_TAG }}

      - name: 上传至阿里云
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'registry.cn-hongkong.aliyuncs.com'
          namespaces: 'danxiaonuo'
          repository_name: 'zabbix-build-mysql'
          user_name: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          image_version: ${{ matrix.DOCKER_TAG }}
          docker_file: 'build-mysql/.'


      - name: 删除旧的GitHub-workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1    #保留多少个workflow不删除

  zabbix-server:
    # 依赖环境
    needs: [ zabbix-build-mysql ]
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_TAG: latest

    # 运行步骤
    steps:

      # 检出master分支
      - name: 检出各个模块代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: 安装 docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建镜像并发布
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./zabbix-server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zabbix-server:${{ matrix.DOCKER_TAG }}

      - name: 上传至阿里云
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'registry.cn-hongkong.aliyuncs.com'
          namespaces: 'danxiaonuo'
          repository_name: 'zabbix-server'
          user_name: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          image_version: ${{ matrix.DOCKER_TAG }}
          docker_file: 'zabbix-server/.'


      - name: 删除旧的GitHub-workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1    #保留多少个workflow不删除

  zabbix-proxy:
    # 依赖环境
    needs: [ zabbix-build-mysql ]
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_TAG: latest

    # 运行步骤
    steps:

      # 检出master分支
      - name: 检出各个模块代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: 安装 docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建镜像并发布
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./zabbix-proxy/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zabbix-proxy:${{ matrix.DOCKER_TAG }}

      - name: 上传至阿里云
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'registry.cn-hongkong.aliyuncs.com'
          namespaces: 'danxiaonuo'
          repository_name: 'zabbix-proxy'
          user_name: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          image_version: ${{ matrix.DOCKER_TAG }}
          docker_file: 'zabbix-proxy/.'


      - name: 删除旧的GitHub-workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1    #保留多少个workflow不删除

  zabbix-agent2:
    # 依赖环境
    needs: [ zabbix-build-mysql ]
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_TAG: latest

    # 运行步骤
    steps:

      # 检出master分支
      - name: 检出各个模块代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: 安装 docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建镜像并发布
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./zabbix-agent2/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zabbix-agent2:${{ matrix.DOCKER_TAG }}

      - name: 上传至阿里云
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'registry.cn-hongkong.aliyuncs.com'
          namespaces: 'danxiaonuo'
          repository_name: 'zabbix-agent2'
          user_name: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          image_version: ${{ matrix.DOCKER_TAG }}
          docker_file: 'zabbix-agent2/.'

      - name: 删除旧的GitHub-workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1    #保留多少个workflow不删除

  zabbix-web-service:
    # 依赖环境
    needs: [ zabbix-build-mysql ]
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_TAG: latest

    # 运行步骤
    steps:

      # 检出master分支
      - name: 检出各个模块代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: 安装 docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建镜像并发布
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zabbix-web-service:${{ matrix.DOCKER_TAG }}

      - name: 上传至阿里云
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'registry.cn-hongkong.aliyuncs.com'
          namespaces: 'danxiaonuo'
          repository_name: 'zabbix-web-service'
          user_name: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          image_version: ${{ matrix.DOCKER_TAG }}
          docker_file: 'web-service/.'

      - name: 删除旧的GitHub-workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1    #保留多少个workflow不删除

  zabbix-web-nginx:
    # 依赖环境
    needs: [ zabbix-build-mysql ]
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_TAG: latest

    # 运行步骤
    steps:

      # 检出master分支
      - name: 检出各个模块代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: 安装 docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建镜像并发布
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-nginx/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zabbix-web-nginx:${{ matrix.DOCKER_TAG }}

      - name: 上传至阿里云
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'registry.cn-hongkong.aliyuncs.com'
          namespaces: 'danxiaonuo'
          repository_name: 'zabbix-web-nginx'
          user_name: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          image_version: ${{ matrix.DOCKER_TAG }}
          docker_file: 'web-nginx/.'

      - name: 删除旧的GitHub-workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1    #保留多少个workflow不删除

  zabbix-snmptraps:
    # 依赖环境
    needs: [ zabbix-build-mysql ]
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_TAG: latest

    # 运行步骤
    steps:

      # 检出master分支
      - name: 检出各个模块代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: 安装 docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建镜像并发布
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./snmptraps/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zabbix-snmptraps:${{ matrix.DOCKER_TAG }}

      - name: 上传至阿里云
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'registry.cn-hongkong.aliyuncs.com'
          namespaces: 'danxiaonuo'
          repository_name: 'zabbix-snmptraps'
          user_name: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          image_version: ${{ matrix.DOCKER_TAG }}
          docker_file: 'snmptraps/.'


      - name: 删除旧的GitHub-workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1    #保留多少个workflow不删除

  zabbix-java-gateway:
    # 依赖环境
    needs: [ zabbix-build-mysql ]
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_TAG: latest

    # 运行步骤
    steps:

      # 检出master分支
      - name: 检出各个模块代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: 安装 docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建镜像并发布
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./java-gateway/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zabbix-java-gateway:${{ matrix.DOCKER_TAG }}

      - name: 上传至阿里云
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'registry.cn-hongkong.aliyuncs.com'
          namespaces: 'danxiaonuo'
          repository_name: 'zabbix-java-gateway'
          user_name: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          image_version: ${{ matrix.DOCKER_TAG }}
          docker_file: 'java-gateway/.'


      - name: 删除旧的GitHub-workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1    #保留多少个workflow不删除
